version: '3.9'
services: 

  frontend:
    build:
      context: ./frontend
    # env_file:
      # - ./frontend/.env
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    networks:
      - webapp
    ports:
      - "4200:4200"
    stdin_open: true
    restart: always
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "3000:3000" # custom backend nestjs port
      - "5500:5500" 
      - "5555:5555" # prisma
    environment:
      - DB_URL=postgresql://user:password123@db:5432/postgres_db?schema=public
    volumes:
      - ./backend/prisma:/backend/prisma # for dev experience, remove for prod
      - ./backend/src:/backend/src # for dev experience, remove for prod
    networks:
      - database
      - webapp
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - PGUSER=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres_dbw
    networks:
      - database

volumes:
  db_volume:
  front_volume:
networks:
  database:
    driver: bridge
  webapp:
    driver: bridge